/*
 * sensor.c
 *
 *  Created on: Oct 16, 2025
 *      Author: ordum
 */


#include "sensor.h"
#include "config.h"
#include "stm32g4xx_hal.h"
#include <string.h>


extern ADC_HandleTypeDef hadc1; // from main generated by Cube


static uint32_t adcRaw[ADC_CHANNEL_COUNT];
static SensorValues_t sensorValues;


void sensorInit(void)
{
memset(&sensorValues,0,sizeof(sensorValues));
for(uint8_t i=0;i<ADC_CHANNEL_COUNT;i++) adcRaw[i]=0;
}


void sensorStartADC(void)
{
// Start ADC in DMA or interrupt mode depending on your CubeMX setup.
// Here we start regular conversion with DMA assumed configured to fill adcRaw.
HAL_ADC_Start_DMA(&hadc1, (uint32_t*)adcRaw, ADC_CHANNEL_COUNT);
}


void sensorPoll(void)
{
// Convert raw ADC to physical values. Channel mapping must match CubeMX.
// Example mapping:
// adcRaw[0] - currentInput
// adcRaw[1] - currentOutput
// adcRaw[2] - currentChoke
// adcRaw[3] - voltageIn
// adcRaw[4] - voltageOut


float factor = VREF_VOLTS / ADC_RESOLUTION;
float v0;


// currents
v0 = adcRaw[0]*factor;
sensorValues.currentInput_mA = (int32_t)(((v0 - CURRENT_SENSOR_OFFSET_VOLTS)/CURRENT_SHUNT_GAIN)*1000.0f);


v0 = adcRaw[1]*factor;
sensorValues.currentOutput_mA = (int32_t)(((v0 - CURRENT_SENSOR_OFFSET_VOLTS)/CURRENT_SHUNT_GAIN)*1000.0f);


v0 = adcRaw[2]*factor;
sensorValues.currentChoke_mA = (int32_t)(((v0 - CURRENT_SENSOR_OFFSET_VOLTS)/CURRENT_SHUNT_GAIN)*1000.0f);


// voltages
v0 = adcRaw[3]*factor;
sensorValues.voltageIn_mV = (int32_t)((v0 * VOLTAGE_DIVIDER_RATIO) * 1000.0f);


v0 = adcRaw[4]*factor;
sensorValues.voltageOut_mV = (int32_t)((v0 * VOLTAGE_DIVIDER_RATIO) * 1000.0f);
}


const SensorValues_t* sensorGetValues(void)
{
return &sensorValues;
}
