Converter Control System: Src/can.c File Reference
can.c File Reference
Модуль работы с CAN-шиной (FDCAN)
#include "main.h"
#include "can.h"
#include <string.h>
Functions
void canInit (void)
Инициализация CAN-модулей
void canProcessPeriodic ()
Периодическая обработка CAN.
void canHeartbeat (void)
Отправка heartbeat-сообщения
void canPublishTelemetry (SystemState_t state, uint32_t errorMask, const SensorValues_t *s)
Публикация телеметрии по CAN.
void canReceiveHandler (FDCAN_HandleTypeDef *hfdcan)
Обработчик принятых CAN-сообщений
void HAL_FDCAN_RxFifo0Callback (FDCAN_HandleTypeDef *hfdcan, uint32_t RxFifo0ITs)
Callback-функция прерывания по приему в FIFO0.
void canRecoverFromBusOff (FDCAN_HandleTypeDef *hfdcan)
Восстановление после состояния Bus-Off.
void canCheckStatus (void)
Проверка статуса CAN-шины
Variables
uint8_t can_init = 0
Флаг инициализации CAN модуля
float targetVoltage = 0.0f
Целевое напряжение, полученное по CAN.
SystemState_t requestedMode = STATE_IDLE
Запрошенный режим работы системы, полученный по CAN.
FDCAN_HandleTypeDef hfdcan1
Внешние дескрипторы FDCAN (определены в main.c)
Detailed Description
Модуль работы с CAN-шиной (FDCAN)
Этот модуль предоставляет функции для инициализации, отправки и приема сообщений по двум CAN-шинам (FDCAN1 и FDCAN2), а также восстановления после ошибок.
Definition in file can.c.
Function Documentation
canCheckStatus()
void canCheckStatus (void)
Проверка статуса CAN-шины
Проверка статуса CAN-шин
Проверяет состояние обеих CAN-шин на наличие ошибок Bus-Off. При обнаружении ошибки выполняет восстановление и мигает светодиодом.
Note
Вызывается периодически для мониторинга состояния CAN-шин
Definition at line 315 of file can.c.
References canRecoverFromBusOff(), and hfdcan1.
canHeartbeat()
void canHeartbeat (void)
Отправка heartbeat-сообщения
Отправляет heartbeat-сообщение с ID 0x120 по очереди на CAN1 или CAN2. Сообщение содержит один байт данных (0x00).
Note
Использует стандартный идентификатор, классический CAN формат
Definition at line 96 of file can.c.
References hfdcan1.
canInit()
void canInit (void)
Инициализация CAN-модулей
Инициализация обеих шин FDCAN (FDCAN1 и FDCAN2)
Функция выполняет инициализацию двух CAN-шин (FDCAN1 и FDCAN2):
Запуск CAN2 с задержкой после CAN1
Настройка глобальных фильтров
Активация прерываний
Note
Порядок запуска важен: сначала CAN1, затем с задержкой CAN2
Warning
При ошибке инициализации вызывается Error_Handler()
Definition at line 43 of file can.c.
References can_init, Error_Handler(), and hfdcan1.
Referenced by main().
canProcessPeriodic()
void canProcessPeriodic (void)
Периодическая обработка CAN.
Переключает флаг выбора шины для отправки сообщений. Вызывается периодически для чередования отправки между CAN1 и CAN2.
Definition at line 83 of file can.c.
canPublishTelemetry()
void canPublishTelemetry (SystemState_t state, uint32_t errorMask, const SensorValues_t * s)
Публикация телеметрии по CAN.
Отправка телеметрии по CAN.
Отправляет телеметрийные данные системы с ID 0x123. Формат данных:
Байт 0: Состояние системы (SystemState_t)
Байт 1: Маска ошибок (младший байт)
Байты 2-3: Входное напряжение (int16_t)
Байты 4-5: Выходное напряжение (int16_t)
Байты 6-7: Выходной ток (int16_t)
Parameters
state Текущее состояние системы
errorMask Маска ошибок системы
s Указатель на структуру сенсорных значений
Note
Если модуль CAN не инициализирован, функция ничего не делает
Definition at line 151 of file can.c.
References can_init, SensorValues_t::currentOut, hfdcan1, SensorValues_t::voltageIn, and SensorValues_t::voltageOut.
Referenced by converterProcess().
canReceiveHandler()
void canReceiveHandler (FDCAN_HandleTypeDef * hfdcan)
Обработчик принятых CAN-сообщений
Обрабатывает входящие сообщения с идентификатором 0x666. Формат данных:
Байт 0: Запрошенный режим работы системы
Байты 1-2: Целевое напряжение (int16_t, в децивольтах)
Parameters
hfdcan Указатель на дескриптор FDCAN, от которого получено сообщение
Note
При получении корректного сообщения мигает светодиод LED1
Definition at line 219 of file can.c.
References requestedMode, and targetVoltage.
Referenced by HAL_FDCAN_RxFifo0Callback().
canRecoverFromBusOff()
void canRecoverFromBusOff (FDCAN_HandleTypeDef * hfdcan)
Восстановление после состояния Bus-Off.
Выполняет процедуру восстановления CAN-контроллера после ошибки Bus-Off:
Остановка контроллера
Задержка 100 мс
Повторный запуск контроллера
Настройка фильтров
Активация прерываний
Parameters
hfdcan Указатель на дескриптор FDCAN для восстановления
Note
Для полного сброса может потребоваться вызов MX_FDCANx_Init()
Definition at line 270 of file can.c.
Referenced by canCheckStatus().
HAL_FDCAN_RxFifo0Callback()
void HAL_FDCAN_RxFifo0Callback (FDCAN_HandleTypeDef * hfdcan, uint32_t RxFifo0ITs)
Callback-функция прерывания по приему в FIFO0.
Вызывается при получении нового сообщения в RX FIFO0.
Parameters
hfdcan Указатель на дескриптор FDCAN
RxFifo0ITs Маска прерываний FIFO0
Definition at line 251 of file can.c.
References canReceiveHandler().
Variable Documentation
targetVoltage
float targetVoltage = 0.0f
Целевое напряжение, полученное по CAN.
Целевое напряжение, полученное по CAN (в вольтах)
Definition at line 17 of file can.c.
Referenced by canReceiveHandler().