Converter Control System: Src/converter.c File Reference
converter.c File Reference
Основной модуль управления преобразователем
#include "converter.h"
#include "sensor.h"
#include "diag.h"
#include "pid.h"
#include "pwmHandler.h"
#include "precharge.h"
#include "pwm.h"
#include "config.h"
#include "types.h"
#include "can.h"
#include <stdio.h>
#include <stdint.h>
Functions
void converterInit (void)
Инициализация преобразователя
SystemState_t ConverterGetState (void)
Получение текущего состояния системы
void converterProcess (SystemState_t state)
Основной процесс управления преобразователем
Variables
SystemState_t currentState = STATE_INIT
Текущее состояние системы преобразователя
PIController_t currentPid
ПИ-регулятор для управления преобразователем
uint32_t lastMode = 0xFFFFFFFF
Последний обработанный режим работы (для обнаружения изменений)
Detailed Description
Основной модуль управления преобразователем
Этот модуль реализует главный цикл управления преобразователем, включая обработку состояний системы, диагностику, PID-регулирование и взаимодействие с периферийными модулями.
Author
ordum
Date
Oct 16, 2025
Definition in file converter.c.
Function Documentation
ConverterGetState()
SystemState_t ConverterGetState (void)
Получение текущего состояния системы
Возвращает текущее состояние преобразователя.
Returns
Текущее состояние системы (SystemState_t)
Return values
STATE_INIT Состояние инициализации
STATE_PRECHARGE Состояние предзаряда
STATE_IDLE Холостой режим
STATE_CHARGE Режим заряда
STATE_DISCHARGE Режим разряда
Definition at line 90 of file converter.c.
References currentState.
converterInit()
void converterInit (void)
Инициализация преобразователя
Выполняет начальную инициализацию всех подсистем преобразователя:
Инициализация датчиков
Инициализация диагностики
Инициализация предзаряда
Настройка ПИ-регулятора с параметрами ШИМ
Отключение ШИМ до проверки безопасности
Note
Должна быть вызвана один раз при старте системы
Warning
ШИМ отключен до завершения инициализации
Definition at line 63 of file converter.c.
References CONTROL_DT_MS, currentPid, diagInit(), piInit(), prechargeInit(), pwmDisable(), pwmGetArr(), and sensorInit().
converterProcess()
void converterProcess (SystemState_t state)
Основной процесс управления преобразователем
Выполняет один цикл управления преобразователем:
Получение данных с датчиков
Проверка диагностики
Обработка изменений режима работы
Управление ШИМ в зависимости от состояния
ПИ-регулирование в режимах заряда/разряда
Управление предзарядом
Публикация телеметрии по CAN
Parameters
state Запрошенное состояние системы для перехода
Note
Функция вызывается периодически с периодом CONTROL_DT_MS
Warning
При обнаружении ошибок система переходит в состояние INIT
Note
В режиме TEST_UNITY используется заглушечная диагностика
Definition at line 112 of file converter.c.
References canPublishTelemetry(), SensorValues_t::currentOut, currentPid, currentPWMState, currentState, diagCheck(), ERR_NONE, lastMode, piReset(), piUpdate(), prechargeStart(), pwmHandlerProcess(), pwmSetDuty(), sensorGetValues(), STATE_CHARGE, STATE_DISCHARGE, STATE_IDLE, STATE_INIT, STATE_PRECHARGE, and SensorValues_t::voltageOut.
Variable Documentation
currentState
SystemState_t currentState = STATE_INIT
Текущее состояние системы преобразователя
Внешняя переменная текущего состояния системы
Definition at line 41 of file converter.c.
Referenced by ConverterGetState(), converterProcess(), and pwmHandlerProcess().