Converter Control System: Src/flash.c File Reference
flash.c File Reference
Модуль работы с FLASH памятью
#include "flash.h"
#include <string.h>
Functions
HAL_StatusTypeDef Flash_Erase (void)
Стирание пользовательской области FLASH.
HAL_StatusTypeDef Flash_WriteVars (const FlashVars_t *vars)
Запись калибровочных данных во FLASH.
void Flash_ReadVars (FlashVars_t *vars)
Чтение калибровочных данных из FLASH.
Detailed Description
Модуль работы с FLASH памятью
Этот модуль предоставляет функции для чтения, записи и стирания калибровочных данных во FLASH памяти микроконтроллера STM32G4.
Definition in file flash.c.
Function Documentation
Flash_Erase()
HAL_StatusTypeDef Flash_Erase (void)
Стирание пользовательской области FLASH.
Выполняет стирание одной страницы FLASH (2 КБ) по адресу FLASH_USER_START_ADDR. Используется для подготовки области к записи новых калибровочных данных.
Алгоритм:
Определение номера страницы по адресу
Отключение прерываний
Разблокировка FLASH
Стирание страницы
Блокировка FLASH
Включение прерываний
Returns
Статус операции
Return values
HAL_OK Страница успешно стерта
HAL_ERROR Ошибка стирания или проверки
Note
Размер страницы FLASH для STM32G4 составляет 2 КБ
Warning
Все данные в странице будут безвозвратно удалены
Definition at line 33 of file flash.c.
References FLASH_USER_START_ADDR.
Referenced by SensorCalibration().
Flash_ReadVars()
void Flash_ReadVars (FlashVars_t * vars)
Чтение калибровочных данных из FLASH.
Считывает структуру FlashVars_t из FLASH памяти по заданному адресу. Используется при инициализации системы для загрузки калибровочных коэффициентов.
Parameters
vars Указатель на структуру для сохранения считанных данных
Note
Функция выполняет простое копирование данных из FLASH в RAM
Не проверяет валидность данных (например, с помощью контрольной суммы)
Для повышения надежности рекомендуется добавить проверку CRC
Definition at line 132 of file flash.c.
References FLASH_USER_START_ADDR, and vars.
Referenced by SensorCalibration(), and sensorInit().
Flash_WriteVars()
HAL_StatusTypeDef Flash_WriteVars (const FlashVars_t * vars)
Запись калибровочных данных во FLASH.
Записывает структуру FlashVars_t во FLASH память с выравниванием на 8 байт. Используется для сохранения калибровочных коэффициентов после калибровки.
Алгоритм:
Выравнивание данных на границу 8 байт
Отключение прерываний
Разблокировка FLASH
Последовательная запись doubleword (64-bit) слов
Блокировка FLASH
Включение прерываний
Parameters
vars Указатель на структуру с калибровочными данными для записи
Returns
Статус операции
Return values
HAL_OK Данные успешно записаны
HAL_ERROR Ошибка при записи данных
Note
Требует предварительного стирания страницы функцией Flash_Erase()
FLASH память поддерживает только запись 1→0, поэтому стирание обязательно
Warning
Максимальная частота записи FLASH ограничена (см. документацию STM32G4)
Definition at line 89 of file flash.c.
References FLASH_USER_START_ADDR, and vars.
Referenced by SensorCalibration().