Converter Control System: Src/kalmanFilter.c File Reference
kalmanFilter.c File Reference
Модуль реализации фильтра Калмана для одномерного сигнала
#include "kalmanFilter.h"
#include <string.h>
Functions
void kalmanInit (KalmanFilter *kf, float q, float r, float initial_value, float initial_error)
Инициализация фильтра Калмана
float kalmanFilter (KalmanFilter *kf, float measurement)
Фильтрация одного измерения
void kalmanFilterArray (KalmanFilter *kf, float *input, float *output, uint32_t size)
Фильтрация массива измерений
float kalmanGetLastValue (KalmanFilter *kf)
Получение последнего отфильтрованного значения
Detailed Description
Модуль реализации фильтра Калмана для одномерного сигнала
Этот модуль предоставляет реализацию одномерного дискретного фильтра Калмана для сглаживания зашумленных измерений. Фильтр основан на простой модели постоянного состояния (constant state model).
Author
ordum
Date
Dec 18, 2025
Definition in file kalmanFilter.c.
Function Documentation
kalmanFilter()
float kalmanFilter (KalmanFilter * kf, float measurement)
Фильтрация одного измерения
Применяет один шаг фильтра Калмана к новому измерению. Алгоритм состоит из двух этапов:
Этап предсказания (prediction): обновление оценки состояния и ковариации
Этап обновления (update): коррекция на основе нового измерения
Математическая модель:
Модель состояния: xₖ = xₖ₋₁ (постоянное состояние)
Модель измерения: zₖ = xₖ + vₖ, где vₖ ~ N(0, r)
Parameters
kf Указатель на структуру фильтра Калмана
measurement Новое измерение для фильтрации
Returns
Отфильтрованное значение
Note
Если kf == NULL, возвращает исходное измерение без фильтрации
Фильтр использует простую модель постоянного состояния
Definition at line 64 of file kalmanFilter.c.
References KalmanFilter::k, KalmanFilter::last_x, KalmanFilter::p, KalmanFilter::q, KalmanFilter::r, and KalmanFilter::x.
Referenced by kalmanFilterArray(), SensorCalibration(), and sensorRead().
kalmanFilterArray()
void kalmanFilterArray (KalmanFilter * kf, float * input, float * output, uint32_t size)
Фильтрация массива измерений
Фильтрация массива значений
Применяет фильтр Калмана ко всем элементам входного массива и сохраняет результаты в выходной массив.
Parameters
kf Указатель на структуру фильтра Калмана
input Указатель на входной массив измерений
output Указатель на выходной массив для сохранения отфильтрованных значений
size Количество элементов в массивах
Note
Если любой из указателей равен NULL или size = 0, функция ничего не делает
Входной и выходной массивы могут быть одним и тем же массивом (in-place обработка)
Warning
Размер выходного массива должен быть не меньше размера входного
Definition at line 95 of file kalmanFilter.c.
References kalmanFilter().
kalmanGetLastValue()
float kalmanGetLastValue (KalmanFilter * kf)
Получение последнего отфильтрованного значения
Получение последней отфильтрованной величины
Возвращает последнее значение, рассчитанное фильтром Калмана. Полезно для отладки или когда нужно получить текущее состояние без обработки нового измерения.
Parameters
kf Указатель на структуру фильтра Калмана
Returns
Последнее отфильтрованное значение
Return values
0.0f если kf == NULL
Note
Функция не изменяет состояние фильтра
Значение сохраняется при каждом вызове kalmanFilter()
Definition at line 118 of file kalmanFilter.c.
References KalmanFilter::last_x.
kalmanInit()
void kalmanInit (KalmanFilter * kf, float q, float r, float initial_value, float initial_error)
Инициализация фильтра Калмана
Устанавливает начальные параметры фильтра Калмана:
Шум процесса (q) - определяет, насколько быстро фильтр реагирует на изменения
Шум измерений (r) - определяет доверие к измерениям
Начальное состояние (initial_value) - начальная оценка сигнала
Начальная ошибка (initial_error) - начальная неопределенность оценки
Parameters
kf Указатель на структуру фильтра Калмана
q Ковариация шума процесса (чем больше, тем быстрее реакция на изменения)
r Ковариация шума измерений (чем больше, тем больше сглаживание)
initial_value Начальное значение оценки состояния
initial_error Начальная ковариация ошибки оценки
Note
Рекомендуемые значения: q = 0.001, r = 2.0 для плавного сглаживания
Warning
Если kf == NULL, функция ничего не делает
Definition at line 34 of file kalmanFilter.c.
References KalmanFilter::k, KalmanFilter::last_x, KalmanFilter::p, KalmanFilter::q, KalmanFilter::r, and KalmanFilter::x.
Referenced by initKalmanFilters().