Converter Control System: Src/pid.c File Reference
pid.c File Reference
Модуль ПИ-регуляторов (одиночного и каскадного)
#include "pid.h"
Functions
void piInit (PIController_t *pi, float kp, float ki, float dt, float outMin, float outMax)
Инициализация одиночного ПИ-регулятора
unsigned int piUpdate (PIController_t *pi, float setpoint, float measurement)
Обновление одиночного ПИ-регулятора
void piReset (PIController_t *pi)
Сброс одиночного ПИ-регулятора
void pi2Init (PI2Controller_t *pi2, float kp_v, float ki_v, float kp_i, float ki_i, float dt, float inMin, float inMax, float outMin, float outMax)
Инициализация каскадного ПИ-регулятора
unsigned int pi2Update (PI2Controller_t *pi2, float voltageSet, float voltageMeas, float currentMeas)
Обновление каскадного ПИ-регулятора
void pi2Reset (PI2Controller_t *pi2)
Сброс каскадного ПИ-регулятора
Detailed Description
Модуль ПИ-регуляторов (одиночного и каскадного)
Этот модуль предоставляет реализацию пропорционально-интегральных регуляторов для систем управления. Включает как одиночный ПИ-регулятор, так и каскадную структуру (внешний контур по напряжению, внутренний по току).
Author
ordum
Date
Oct 16, 2025
Definition in file pid.c.
Function Documentation
pi2Init()
void pi2Init (PI2Controller_t * pi2, float kp_v, float ki_v, float kp_i, float ki_i, float dt, float inMin, float inMax, float outMin, float outMax)
Инициализация каскадного ПИ-регулятора
Инициализирует двухконтурную структуру:
Внешний контур: регулирование напряжения
Внутренний контур: регулирование тока
Parameters
pi2 Указатель на структуру каскадного регулятора
kp_v Коэффициент Kp внешнего контура (напряжение)
ki_v Коэффициент Ki внешнего контура (напряжение)
kp_i Коэффициент Kp внутреннего контура (ток)
ki_i Коэффициент Ki внутреннего контура (ток)
dt Временной шаг дискретизации (секунды)
inMin Минимальное значение для внешнего контура
inMax Максимальное значение для внешнего контура
outMin Минимальное значение для внутреннего контура
outMax Максимальное значение для внутреннего контура
Note
Внутренний контур должен быть быстрее внешнего (большая полоса)
Definition at line 122 of file pid.c.
References PI2Controller_t::currentLoop, piInit(), and PI2Controller_t::voltageLoop.
pi2Reset()
void pi2Reset (PI2Controller_t * pi2)
Сброс каскадного ПИ-регулятора
Сбрасывает внутреннее состояние обоих контуров регулятора
Parameters
pi2 Указатель на структуру каскадного регулятора
Definition at line 168 of file pid.c.
References PI2Controller_t::currentLoop, piReset(), and PI2Controller_t::voltageLoop.
pi2Update()
unsigned int pi2Update (PI2Controller_t * pi2, float voltageSet, float voltageMeas, float currentMeas)
Обновление каскадного ПИ-регулятора
Выполняет один шаг расчета каскадного регулятора:
Внешний контур (напряжение) вычисляет задание по току
Внутренний контур (ток) вычисляет выходное воздействие
Parameters
pi2 Указатель на структуру каскадного регулятора
voltageSet Заданное напряжение (уставка внешнего контура)
voltageMeas Измеренное напряжение (обратная связь внешнего контура)
currentMeas Измеренный ток (обратная связь внутреннего контура)
Returns
Выходной сигнал регулятора (например, скважность ШИМ)
Note
Выход внешнего контура является уставкой для внутреннего контура
Такая структура обеспечивает лучшую динамику и устойчивость
Definition at line 148 of file pid.c.
References PI2Controller_t::currentLoop, piUpdate(), and PI2Controller_t::voltageLoop.
piInit()
void piInit (PIController_t * pi, float kp, float ki, float dt, float outMin, float outMax)
Инициализация одиночного ПИ-регулятора
Устанавливает параметры ПИ-регулятора и сбрасывает внутреннее состояние.
Parameters
pi Указатель на структуру ПИ-регулятора
kp Коэффициент пропорциональной составляющей
ki Коэффициент интегральной составляющей
dt Временной шаг дискретизации (секунды)
outMin Минимальное значение выходного сигнала
outMax Максимальное значение выходного сигнала
Note
Коэффициенты должны быть подобраны для конкретной системы
Warning
При dt=0 может вызвать деление на ноль
Definition at line 34 of file pid.c.
References PIController_t::dt, PIController_t::integral, PIController_t::ki, PIController_t::kp, PIController_t::outMax, PIController_t::outMin, and PIController_t::output.
Referenced by converterInit(), and pi2Init().
piReset()
void piReset (PIController_t * pi)
Сброс одиночного ПИ-регулятора
Сбрасывает внутреннее состояние регулятора (интегратор и выход)
Parameters
pi Указатель на структуру ПИ-регулятора
Note
Используется при изменении режима работы системы
Warning
Сброс во время работы может вызвать скачок выходного сигнала
Definition at line 92 of file pid.c.
References PIController_t::integral, and PIController_t::output.
Referenced by converterProcess(), and pi2Reset().
piUpdate()
unsigned int piUpdate (PIController_t * pi, float setpoint, float measurement)
Обновление одиночного ПИ-регулятора
Выполняет один шаг расчета ПИ-регулятора:
Вычисление ошибки регулирования
Интегрирование ошибки
Применение антивиндапа (anti-windup)
Расчет выходного сигнала
Ограничение выходного сигнала
Parameters
pi Указатель на структуру ПИ-регулятора
setpoint Заданное значение (уставка)
measurement Измеренное значение (обратная связь)
Returns
Выходной сигнал регулятора (ограниченный)
Note
Реализует дискретную форму ПИ-регулятора: u(t) = Kp*e(t) + Ki*∫e(t)dt
Warning
При больших Ki и dt может возникнуть переполнение интегратора
Definition at line 63 of file pid.c.
References PIController_t::dt, PIController_t::integral, PIController_t::ki, PIController_t::kp, PIController_t::outMax, PIController_t::outMin, and PIController_t::output.
Referenced by converterProcess(), and pi2Update().