Converter Control System: Src/pwmHandler.c File Reference
pwmHandler.c File Reference
Модуль обработчика состояний ШИМ
#include "pwmHandler.h"
#include "pwm.h"
#include "diag.h"
Functions
void pwmHandlerProcess (uint8_t hasError, SystemState_t state)
Обработка состояния ШИМ на основе системных условий
Variables
SystemState_t currentState
Внешняя переменная текущего состояния системы
Detailed Description
Модуль обработчика состояний ШИМ
Этот модуль реализует логику управления состоянием ШИМ в зависимости от текущего состояния системы и наличия ошибок. Определяет когда включать и отключать ШИМ на основе системных условий.
Author
ordum
Date
Oct 16, 2025
Definition in file pwmHandler.c.
Function Documentation
pwmHandlerProcess()
void pwmHandlerProcess (uint8_t hasError, SystemState_t state)
Обработка состояния ШИМ на основе системных условий
Обработка состояния ШИМ
Определяет необходимость включения/отключения ШИМ на основе:
Наличия ошибок диагностики
Текущего состояния системы
Запрошенного состояния перехода
Логика работы:
При любой ошибке - ШИМ отключается, система переходит в INIT
В состояниях INIT, IDLE, PRECHARGE - ШИМ отключен
В состояниях CHARGE, DISCHARGE - ШИМ включен
Parameters
hasError Флаг наличия ошибок в системе (1 = есть ошибки, 0 = ошибок нет)
state Запрошенное состояние системы для перехода
Note
Функция обновляет глобальную переменную currentState
Warning
При обнаружении ошибок система принудительно переходит в STATE_INIT
Note
Состояние PRECHARGE считается безопасным для отключения ШИМ
See also
SystemState_t для описания возможных состояний
diagCheck() для получения флага ошибок
Definition at line 44 of file pwmHandler.c.
References currentState, pwmDisable(), pwmEnable(), STATE_CHARGE, STATE_DISCHARGE, STATE_IDLE, STATE_INIT, and STATE_PRECHARGE.
Referenced by converterProcess().
Variable Documentation
currentState
SystemState_t currentState extern
Внешняя переменная текущего состояния системы
Внешняя переменная текущего состояния системы
Definition at line 41 of file converter.c.
Referenced by ConverterGetState(), converterProcess(), and pwmHandlerProcess().