Converter Control System: Src/pwm.c File Reference
pwm.c File Reference
Модуль управления ШИМ (широтно-импульсной модуляцией)
#include "pwm.h"
#include "stm32g4xx_hal.h"
#include "config.h"
Functions
void pwmSetDuty (uint32_t duty)
Установка скважности ШИМ
uint32_t pwmGetArr (void)
Получение значения регистра ARR таймера
void pwmEnable (void)
Включение ШИМ
void pwmDisable (void)
Отключение ШИМ
Variables
TIM_HandleTypeDef htim1
Внешний дескриптор таймера TIM1, настроенного для ШИМ
PWMState_t currentPWMState = STATE_DISABLE
Текущее состояние ШИМ (включен/выключен)
Detailed Description
Модуль управления ШИМ (широтно-импульсной модуляцией)
Этот модуль предоставляет функции для управления ШИМ-сигналами на таймере TIM1 микроконтроллера STM32G4. Используется для управления силовыми ключами преобразователя.
Author
ordum
Date
Oct 16, 2025
Definition in file pwm.c.
Function Documentation
pwmDisable()
void pwmDisable (void)
Отключение ШИМ
Отключает генерацию ШИМ-сигналов на всех каналах. Используется для аварийного отключения или перехода в безопасное состояние.
Note
Все выходы переходят в неактивное состояние
Функция всегда выполняется, независимо от текущего состояния
Warning
После отключения ШИМ заполнение сохраняется и будет применено при следующем включении
Definition at line 107 of file pwm.c.
References currentPWMState, htim1, and STATE_DISABLE.
Referenced by converterInit(), and pwmHandlerProcess().
pwmEnable()
void pwmEnable (void)
Включение ШИМ
Включает генерацию ШИМ-сигналов на всех каналах:
Канал 1 (TIM_CHANNEL_1) - основной выход
Канал 1N (TIM_CHANNEL_1) - комплементарный выход
Канал 2 (TIM_CHANNEL_2) - основной выход
Канал 2N (TIM_CHANNEL_2) - комплементарный выход
Note
Функция имеет защиту от повторного включения
Используется для управления полумостовой/мостовой схемой
Warning
Включение ШИМ при ненулевом заполнении может вызвать броски тока
Definition at line 82 of file pwm.c.
References currentPWMState, htim1, STATE_DISABLE, and STATE_ENABLE.
Referenced by pwmHandlerProcess().
pwmGetArr()
uint32_t pwmGetArr (void)
Получение значения регистра ARR таймера
Возвращает значение регистра авто-перезагрузки (Auto-Reload Register) таймера TIM1. Это значение определяет максимальное значение для параметра duty в функции pwmSetDuty().
Returns
Значение регистра ARR таймера TIM1
Note
ARR определяет период ШИМ-сигнала
See also
pwmSetDuty() для установки значения заполнения
Definition at line 63 of file pwm.c.
References htim1.
Referenced by converterInit().
pwmSetDuty()
void pwmSetDuty (uint32_t duty)
Установка скважности ШИМ
Устанавливает значение заполнения (duty cycle) для каналов ШИМ. Поддерживает два канала с одинаковым значением заполнения.
Parameters
duty Значение заполнения (0..ARR)
Note
Если duty > ARR, значение ограничивается ARR
Устанавливает одинаковое значение для CH1 и CH2
Warning
Функция не проверяет состояние ШИМ (включен/выключен)
See also
pwmGetArr() для получения максимального значения
Definition at line 40 of file pwm.c.
References htim1.
Referenced by converterProcess().