Converter Control System: Src/sensor.c File Reference
sensor.c File Reference
Модуль работы с датчиками и фильтрацией данных
#include "sensor.h"
#include "config.h"
#include "flash.h"
#include "kalmanFilter.h"
Functions
void initKalmanFilters (void)
Инициализация фильтров Калмана
void sensorInit (void)
Инициализация модуля датчиков
void sensorCalculateCoeff (void)
Вычисление и сохранение калибровочных коэффициентов
void sensorRead (void)
Чтение и обработка данных с датчиков
void SensorCalibration (void)
Процедура калибровки датчиков
const SensorValues_t * sensorGetValues (void)
Получение текущих значений датчиков
Variables
KalmanFilter voltageIn_filter
Фильтр Калмана для входного напряжения
KalmanFilter voltageOut_filter
Фильтр Калмана для выходного напряжения
KalmanFilter currentIn_filter
Фильтр Калмана для входного тока
KalmanFilter currentOut_filter
Фильтр Калмана для выходного тока
KalmanFilter currentChoke_filter
Фильтр Калмана для тока дросселя
KalmanFilter voltageIn_filter0
Вспомогательный фильтр Калмана для калибровки входного напряжения
KalmanFilter voltageOut_filter0
Вспомогательный фильтр Калмана для калибровки выходного напряжения
KalmanFilter currentIn_filter0
Вспомогательный фильтр Калмана для калибровки входного тока
KalmanFilter currentOut_filter0
Вспомогательный фильтр Калмана для калибровки выходного тока
KalmanFilter currentChoke_filter0
Вспомогательный фильтр Калмана для калибровки тока дросселя
ADC_HandleTypeDef hadc1
Внешний дескриптор ADC (определен в main.c)
UART_HandleTypeDef huart3
Внешний дескриптор UART для отладки (определен в main.c)
FlashVars_t varsFromFlash
Структура с калибровочными данными, прочитанными из FLASH.
FlashVars_t vars
Структура с текущими калибровочными данными
Detailed Description
Модуль работы с датчиками и фильтрацией данных
Этот модуль предоставляет функции для чтения, калибровки и фильтрации данных с аналоговых датчиков (напряжения, токи) с использованием фильтра Калмана.
Definition in file sensor.c.
Function Documentation
initKalmanFilters()
void initKalmanFilters (void)
Инициализация фильтров Калмана
Инициализирует все фильтры Калмана для каналов измерения с заданными параметрами:
q (шум процесса) = 0.001f - определяет скорость реакции на изменения
r (шум измерений) = 2.0f - определяет степень сглаживания
initial_value = 0.0f - начальное значение
initial_error = 1.0f - начальная ошибка
Note
Меньшее значение q дает более плавный отклик, меньшее значение r дает большее доверие измерениям
Definition at line 75 of file sensor.c.
References currentChoke_filter, currentChoke_filter0, currentIn_filter, currentIn_filter0, currentOut_filter, currentOut_filter0, kalmanInit(), voltageIn_filter, voltageIn_filter0, voltageOut_filter, and voltageOut_filter0.
Referenced by sensorInit().
sensorCalculateCoeff()
void sensorCalculateCoeff (void)
Вычисление и сохранение калибровочных коэффициентов
Запуск процедуры вычисления калибровочных коэффициентов
Выполняет процедуру калибровки датчиков:
Отключает прерывания на время калибровки
Выполняет многократные измерения для каждого канала
Вычисляет средние значения смещений
Сохраняет коэффициенты во FLASH память
Warning
Функция отключает прерывания на время выполнения калибровки
Note
Калибровка должна выполняться при нулевых входных сигналах
Definition at line 122 of file sensor.c.
References SensorCalibration().
SensorCalibration()
void SensorCalibration (void)
Процедура калибровки датчиков
Выполняет автоматическую калибровку всех датчиков системы:
Накопление большого количества измерений (1000 сэмплов)
Фильтрация через вспомогательные фильтры Калмана
Вычисление средних значений смещений
Сохранение калибровочных коэффициентов во FLASH
Note
Используется 1000 сэмплов для каждого канала
Warning
Стирает и перезаписывает сектор FLASH памяти
Note
В режиме DEBUG выводит информацию об ошибках через UART
Definition at line 204 of file sensor.c.
References ADC_TO_CURRENT_COEFF, ADC_TO_VOLTAGE_COEFF, FlashVars_t::calCur1, FlashVars_t::calCur2, FlashVars_t::calCur3, FlashVars_t::calPerf, FlashVars_t::calVol1, FlashVars_t::calVol2, CURRENT_OFFSET, SensorValues_t::currentChoke, currentChoke_filter0, SensorValues_t::currentIn, currentIn_filter0, SensorValues_t::currentOut, currentOut_filter0, Flash_Erase(), Flash_ReadVars(), Flash_WriteVars(), hadc1, kalmanFilter(), vars, varsFromFlash, VOLTAGE_OFFSET, SensorValues_t::voltageIn, voltageIn_filter0, SensorValues_t::voltageOut, and voltageOut_filter0.
Referenced by sensorCalculateCoeff().
sensorGetValues()
const SensorValues_t * sensorGetValues (void)
Получение текущих значений датчиков
Возвращает указатель на структуру с текущими отфильтрованными значениями всех датчиков.
Returns
Указатель на структуру SensorValues_t с текущими значениями
Note
Структура обновляется при каждом вызове sensorRead()
Definition at line 313 of file sensor.c.
Referenced by converterProcess().
sensorInit()
void sensorInit (void)
Инициализация модуля датчиков
Выполняет начальную настройку модуля:
Чтение калибровочных данных из FLASH
Инициализацию фильтров Калмана
Note
Должна быть вызвана один раз при старте системы
Definition at line 104 of file sensor.c.
References Flash_ReadVars(), initKalmanFilters(), and vars.
Referenced by converterInit(), and main().
sensorRead()
void sensorRead (void)
Чтение и обработка данных с датчиков
Выполняет последовательное чтение всех 5 каналов ADC, преобразование сырых значений в физические величины и их фильтрацию через фильтры Калмана.
Порядок каналов ADC:
[0]: Входное напряжение
[1]: Выходное напряжение
[2]: Входной ток
[3]: Выходной ток
[4]: Ток дросселя
Note
Функция блокирующая, время выполнения зависит от скорости ADC
Warning
Отрицательные значения напряжений обрезаются до нуля
Definition at line 155 of file sensor.c.
References ADC_TO_CURRENT_COEFF, ADC_TO_VOLTAGE_COEFF, FlashVars_t::calCur1, FlashVars_t::calCur2, FlashVars_t::calCur3, FlashVars_t::calVol1, FlashVars_t::calVol2, CURRENT_OFFSET, SensorValues_t::currentChoke, currentChoke_filter, SensorValues_t::currentIn, currentIn_filter, SensorValues_t::currentOut, currentOut_filter, hadc1, kalmanFilter(), vars, VOLTAGE_OFFSET, SensorValues_t::voltageIn, voltageIn_filter, SensorValues_t::voltageOut, and voltageOut_filter.