Converter Control System: Src/stm32g4xx_hal_msp.c File Reference
stm32g4xx_hal_msp.c File Reference
This file provides code for the MSP Initialization and de-Initialization codes.
#include "main.h"
Functions
void HAL_TIM_MspPostInit (TIM_HandleTypeDef *htim)
void HAL_MspInit (void)
void HAL_ADC_MspInit (ADC_HandleTypeDef *hadc)
ADC MSP Initialization This function configures the hardware resources used in this example.
void HAL_ADC_MspDeInit (ADC_HandleTypeDef *hadc)
ADC MSP De-Initialization This function freeze the hardware resources used in this example.
void HAL_FDCAN_MspInit (FDCAN_HandleTypeDef *hfdcan)
FDCAN MSP Initialization This function configures the hardware resources used in this example.
void HAL_FDCAN_MspDeInit (FDCAN_HandleTypeDef *hfdcan)
FDCAN MSP De-Initialization This function freeze the hardware resources used in this example.
void HAL_TIM_PWM_MspInit (TIM_HandleTypeDef *htim_pwm)
TIM_PWM MSP Initialization This function configures the hardware resources used in this example.
void HAL_TIM_Base_MspInit (TIM_HandleTypeDef *htim_base)
TIM_Base MSP Initialization This function configures the hardware resources used in this example.
void HAL_TIM_PWM_MspDeInit (TIM_HandleTypeDef *htim_pwm)
TIM_PWM MSP De-Initialization This function freeze the hardware resources used in this example.
void HAL_TIM_Base_MspDeInit (TIM_HandleTypeDef *htim_base)
TIM_Base MSP De-Initialization This function freeze the hardware resources used in this example.
void HAL_UART_MspInit (UART_HandleTypeDef *huart)
UART MSP Initialization This function configures the hardware resources used in this example.
void HAL_UART_MspDeInit (UART_HandleTypeDef *huart)
UART MSP De-Initialization This function freeze the hardware resources used in this example.
Detailed Description
This file provides code for the MSP Initialization and de-Initialization codes.
Attention
Copyright (c) 2025 STMicroelectronics. All rights reserved.
This software is licensed under terms that can be found in the LICENSE file in the root directory of this software component. If no LICENSE file comes with this software, it is provided AS-IS.
Definition in file stm32g4xx_hal_msp.c.
Function Documentation
HAL_ADC_MspDeInit()
void HAL_ADC_MspDeInit (ADC_HandleTypeDef * hadc)
ADC MSP De-Initialization This function freeze the hardware resources used in this example.
Parameters
hadc ADC handle pointer
Return values
None
ADC1 GPIO Configuration PA0 ------> ADC1_IN1 PA1 ------> ADC1_IN2 PA2 ------> ADC1_IN3 PA3 ------> ADC1_IN4 PB14 ------> ADC1_IN5
Definition at line 149 of file stm32g4xx_hal_msp.c.
HAL_ADC_MspInit()
void HAL_ADC_MspInit (ADC_HandleTypeDef * hadc)
ADC MSP Initialization This function configures the hardware resources used in this example.
Parameters
hadc ADC handle pointer
Return values
None
Initializes the peripherals clocks
ADC1 GPIO Configuration PA0 ------> ADC1_IN1 PA1 ------> ADC1_IN2 PA2 ------> ADC1_IN3 PA3 ------> ADC1_IN4 PB14 ------> ADC1_IN5
Definition at line 94 of file stm32g4xx_hal_msp.c.
References Error_Handler().
HAL_FDCAN_MspDeInit()
void HAL_FDCAN_MspDeInit (FDCAN_HandleTypeDef * hfdcan)
FDCAN MSP De-Initialization This function freeze the hardware resources used in this example.
Parameters
hfdcan FDCAN handle pointer
Return values
None
FDCAN1 GPIO Configuration PA11 ------> FDCAN1_RX PA12 ------> FDCAN1_TX
FDCAN2 GPIO Configuration PB12 ------> FDCAN2_RX PB13 ------> FDCAN2_TX
Definition at line 277 of file stm32g4xx_hal_msp.c.
HAL_FDCAN_MspInit()
void HAL_FDCAN_MspInit (FDCAN_HandleTypeDef * hfdcan)
FDCAN MSP Initialization This function configures the hardware resources used in this example.
Parameters
hfdcan FDCAN handle pointer
Return values
None
Initializes the peripherals clocks
FDCAN1 GPIO Configuration PA11 ------> FDCAN1_RX PA12 ------> FDCAN1_TX
Initializes the peripherals clocks
FDCAN2 GPIO Configuration PB12 ------> FDCAN2_RX PB13 ------> FDCAN2_TX
Definition at line 185 of file stm32g4xx_hal_msp.c.
References Error_Handler().
HAL_MspInit()
void HAL_MspInit (void)
Initializes the Global MSP.
Disable the internal Pull-Up in Dead Battery pins of UCPD peripheral
Definition at line 65 of file stm32g4xx_hal_msp.c.
HAL_TIM_Base_MspDeInit()
void HAL_TIM_Base_MspDeInit (TIM_HandleTypeDef * htim_base)
TIM_Base MSP De-Initialization This function freeze the hardware resources used in this example.
Parameters
htim_base TIM_Base handle pointer
Return values
None
Definition at line 468 of file stm32g4xx_hal_msp.c.
HAL_TIM_Base_MspInit()
void HAL_TIM_Base_MspInit (TIM_HandleTypeDef * htim_base)
TIM_Base MSP Initialization This function configures the hardware resources used in this example.
Parameters
htim_base TIM_Base handle pointer
Return values
None
Definition at line 359 of file stm32g4xx_hal_msp.c.
HAL_TIM_MspPostInit()
void HAL_TIM_MspPostInit (TIM_HandleTypeDef * htim)
TIM1 GPIO Configuration PC13 ------> TIM1_CH1N PB0 ------> TIM1_CH2N PA8 ------> TIM1_CH1 PA9 ------> TIM1_CH2
Definition at line 392 of file stm32g4xx_hal_msp.c.
HAL_TIM_PWM_MspDeInit()
void HAL_TIM_PWM_MspDeInit (TIM_HandleTypeDef * htim_pwm)
TIM_PWM MSP De-Initialization This function freeze the hardware resources used in this example.
Parameters
htim_pwm TIM_PWM handle pointer
Return values
None
Definition at line 443 of file stm32g4xx_hal_msp.c.
HAL_TIM_PWM_MspInit()
void HAL_TIM_PWM_MspInit (TIM_HandleTypeDef * htim_pwm)
TIM_PWM MSP Initialization This function configures the hardware resources used in this example.
Parameters
htim_pwm TIM_PWM handle pointer
Return values
None
Definition at line 333 of file stm32g4xx_hal_msp.c.
HAL_UART_MspDeInit()
void HAL_UART_MspDeInit (UART_HandleTypeDef * huart)
UART MSP De-Initialization This function freeze the hardware resources used in this example.
Parameters
huart UART handle pointer
Return values
None
USART3 GPIO Configuration PB10 ------> USART3_TX PB11 ------> USART3_RX
Definition at line 558 of file stm32g4xx_hal_msp.c.
HAL_UART_MspInit()
void HAL_UART_MspInit (UART_HandleTypeDef * huart)
UART MSP Initialization This function configures the hardware resources used in this example.
Parameters
huart UART handle pointer
Return values
None
Initializes the peripherals clocks
USART3 GPIO Configuration PB10 ------> USART3_TX PB11 ------> USART3_RX
Definition at line 507 of file stm32g4xx_hal_msp.c.
References Error_Handler().