name: Ceedling Unit-Tests

on:
  push:
  pull_request:

jobs:
  Unit-Test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'

      - name: Install Ceedling
        run: |
          gem install ceedling

      - name: Run Ceedling tests
        run: |
          ceedling test:all
